INSERT INTO PET (BREED, TYPE, NAME) VALUES ('POODLE',  'DOG', 'Suki');
INSERT INTO PET (BREED, TYPE, NAME) VALUES ('SIAMESE', 'CAT', 'Bing');
INSERT INTO PET (BREED, TYPE, NAME) VALUES ('SIAMESE', 'CAT', 'Bang');
INSERT INTO PET (BREED, TYPE, NAME) VALUES ('POODLE', 'DOG', 'Yak');

INSERT INTO ADOPTER (NAME, PHONE_NUMBER) VALUES ('Alexander Delgado', '123-123-4567');
INSERT INTO ADOPTER (NAME, PHONE_NUMBER) VALUES ('Jennifer Lopez', '123-123-4567');

INSERT INTO ADOPTION (ADOPTION_DATE, PET_ID, ADOPTER_ID) VALUES ('2024-12-10', 1, 1);
INSERT INTO ADOPTION (ADOPTION_DATE, PET_ID, ADOPTER_ID) VALUES ('2024-12-10', 2, 1);
INSERT INTO ADOPTION (ADOPTION_DATE, PET_ID, ADOPTER_ID) VALUES ('2024-12-10', 3, 2);